AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account observability stack

Parameters:
  AwsOamSinkArn:
    Type: String
  DatadogTemplateUrl:
    Type: String
  DatadogSite:
    Type: String
  DatadogApiKey:
    Type: String
    NoEcho: 'true'
  DatadogAppKey:
    Type: String
    NoEcho: 'true'
  DataDogLogsDestinationArn:
    Type: String
    NoEcho: 'true'
  DisableMetricCollection:
    Type: String
    Default: 'false'
  UseMetricsStreaming:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  UseLogsStreaming:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'

Conditions:
  MetricStreamingEnabled: !Equals [ !Ref UseMetricsStreaming, 'true' ]
  LogsStreamingEnabled: !Equals [ !Ref UseLogsStreaming, 'true' ]


Resources:
  DatadogIntegrationStack:
    Type: AWS::Serverless::Application
    Properties:
      # FIXME: Location is hardcoded to work around a bug in SAM. Perhaps we switch to
      # AWS::CloudFormation::Stack resources instead.
      Location: "https://datadog-cloudformation-template.s3.amazonaws.com/aws/v4.2.0/main_organizations.yaml"
      Parameters:
        DatadogApiKey: !Ref DatadogApiKey
        DatadogAppKey: !Ref DatadogAppKey
        DatadogSite: !Ref DatadogSite
        DisableMetricCollection: !Ref DisableMetricCollection

  LogShippingStack:
    Type: AWS::Serverless::Application
    Condition: LogsStreamingEnabled
    Properties:
      Location: "./stacksets/logs/template.yaml"
      Parameters:
        DestinationArn: !Ref DataDogLogsDestinationArn

  MetricsSinkStack:
    Type: AWS::Serverless::Application
    Condition: MetricStreamingEnabled
    Properties:
      Location: "./stacksets/metrics/template-oam-link.yaml"
      Parameters:
        AwsOamSinkArn: !Ref AwsOamSinkArn

  CwCrossAccountShareStack:
    Type: AWS::Serverless::Application
    Condition: MetricStreamingEnabled
    Properties:
      Location: "./stacksets/metrics/template-cw-cross-account-sharing.yaml"
      Parameters:
        Policy: View-Access-for-all-services
        MonitoringAccountId: !Select [ "4", !Split [ ":", !Ref AwsOamSinkArn ] ]
